
input_dir: ./data/short/
truth_dir: ./data/long/
checkpoint_dir: ./checkpoint/
preprocess: False #Set to True to force preprocessing
preprocess_dir: ./data/preprocess/ 
patch_size: 512
save_interval: 5   # epochs
batch_size: 24
initial_learning_rate: 1e-4
epochs: 4000
visualize: False
num_workers: 1
